---
- hosts: all
  vars_files:
    - vars.yml
  become: yes
  tasks:

  - name: Update yum
    command: yum update -y

  - name: Install EPEL
    yum:
      name: epel-release
      state: present

  - name: Install Recommended Packages
    yum: pkg={{item}} state=present
    with_items:
      - make
      - gcc
      - gcc-c++
      - libcurl-devel
      - libxml2-devel
      - java-1.7.0-openjdk-devel
      - openssl-devel
      - openssh-clients

  - name: Install R Dependencies
    command: yum-builddep R -y

  - name: Build R from Source
    include: build-R.yml

  - name: Install R packages
    include: install-packages.yml
